version: 2

updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    rebase-strategy: "disabled"
    schedule:
      interval: "monthly"
    assignees:
      - "NoDocCat"
    reviewers:
      - "NoDocCat"
